development:
  adapter: postgresql
  username: subbarao
  database: payup_development
  host: localhost
test:
    adapter: postgresql
    username: subbarao
    database: payup_test
    host: localhost
